language: python

env:
  - TOXENV=py25
  - TOXENV=py27
  - TOXENV=py33

install:
  - pip install tox
  - pip install coveralls

script: 
  - tox
  - python setup.py test --addopts "-v --cov coveralls --cov-report term-missing"

after_success:
  - coveralls
