build: false
environment:
  matrix:
    - PYTHON: "C:/Python27"
    - PYTHON: "C:/Python34"
init:
  - "ECHO %PYTHON%"
  - ps: "ls C:/Python*"
install:
  - "%PYTHON%/Scripts/pip.exe install -U pip setuptools"
  - "%PYTHON%/Scripts/pip.exe install -e ."
test_script:
  - "%PYTHON%/python.exe setup.py test"
